theme: jekyll-theme-cayman
title: LU, Yanru (Linguist)
description: > # this means to ignore newlines until "show_excerpts:"
  Yanru Lu's personal website
  
show_excerpts: false # set to true to show excerpts on the homepage
show_downloads: false
