theme: jekyll-theme-cayman
title: LU, Yanru 卢晏如
description: Linguist
show_excerpts: false
show_downloads: true
github:
  zip_url: https://github.com/Lu-Yanru/lu-yanru.github.io/download.zip
  another_url: lu-yanru.github.io/cv/
# pages: true
